# Generated by Django 4.0.4 on 2022-05-27 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_course_lesson_coursesteachers'),
    ]

    operations = [
    ]
